((nil . ((indent-tabs-mode . nil)
         (fill-column . 80)
         (mode . auto-fill)))
 (c-mode . ((c-file-style . "linux")
            (c-basic-offset . 4)))
 (c++-mode . ((c-file-style . "linux")
              (c-basic-offset . 4)))
 (cl-mode . ((c-file-style . "linux")
             (c-basic-offset . 4)))
 (cuda-mode . ((c-file-style . "linux")
               (c-basic-offset . 4))))
